MyRead.Web/Pages/Manager/AddAuthor.cshtml.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using MyRead.Core.Entities;
using MyRead.Core.Models;
using MyRead.Data;
using Serilog;

namespace MyRead.Web.Pages.Manager
{
    public class AddAuthorModel : PageModel
    {
        private readonly IData<Author> authorData;
        public AddAuthorModel(IData<Author> authorData)
        {
            this.authorData = authorData;
        }

        [BindProperty]
        public AuthorModel AuthorModel { get; set; } 

        public void OnGet()
        {
            AuthorModel = new AuthorModel();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if(!ModelState.IsValid)
            {
                return Page();
            }

            try
            {
                var authorEntity = CreateNewAuthorEntity();
                await SaveAuthorEntityToDatabaseAsync(authorEntity);
            }
            catch(Exception ex)
            {
                Log.Logger.Error("Exception in AddAuthor OnPostAsync: " + ex);
            }

            return RedirectToPage("./AddBook");
        }

        private Author CreateNewAuthorEntity()
        {
            var authorEntity = new Author
            {
                FirstName = AuthorModel.FirstName,
                LastName = AuthorModel.LastName
            };

            return authorEntity;
        }

        private async Task SaveAuthorEntityToDatabaseAsync(Author authorEntity)
        {
            authorData.Add(authorEntity);
            await authorData.CommitAsync();
        }
    }
}

MyRead.Web/Pages/Manager/AddBook.cshtml.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MyRead.Core.Entities;
using MyRead.Core.Models;
using MyRead.Data;
using Serilog;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace MyRead.Web.Pages.Manager
{
    public class AddBookModel : PageModel
    {
        private readonly IData<Book> bookData;
        private readonly IData<Author> authorData;
        private readonly IWebHostEnvironment environment;

        public AddBookModel(IData<Book> bookData, IData<Author> authorData, IWebHostEnvironment environment)
        {
            this.bookData = bookData;
            this.authorData = authorData;
            this.environment = environment;
        }

        [TempData]
        public string AddNotification { get; set; }

        [Required]
        [BindProperty]
        public IFormFile UploadedPicture { get; set; }

        [BindProperty]
        public BookModel BookModel { get; set; }

        [Required]
        [BindProperty]
        public int AuthorId { get; set; }

        public List<SelectListItem> AuthorSelect { get; set; }

        public async Task OnGetAsync()
        {
            BookModel = new BookModel();
            await PopulateAuthorSelectAsync();
        }

        private async Task PopulateAuthorSelectAsync()
        {
            var authorEntities = await authorData.GetAll()
                .OrderBy(x => x.LastName)
                .ToListAsync(); // Read more about this!
            AuthorSelect = authorEntities.Select(x => new SelectListItem
            {
                Value = x.AuthorID.ToString(),
                Text = $"{x.LastName}, {x.FirstName}"
            }).ToList();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                await PopulateAuthorSelectAsync();
                return Page();
            }

            try
            {
                var imagePath = Path.Combine("images/covers", UploadedPicture.FileName);
                await UploadPictureToFileSystemAsync(imagePath);

                var bookEntity = await CreateNewBookEntityAsync(imagePath);
                await SaveBookEntityToDatabaseAsync(bookEntity);

                AddNotification = $"{bookEntity.Title} added to database";
            }
            catch(Exception ex)
            {
                Log.Logger.Error("Exception in AddBook OnPostAsync: " + ex);
                AddNotification = "Book not added to database, check logs.";
            }

            return RedirectToPage("./ListBook");
        }

        private async Task UploadPictureToFileSystemAsync(string imagePath)
        {
            var file = Path.Combine(environment.WebRootPath, imagePath);
            using (var fileStream = new FileStream(file, FileMode.Create))
            {
                await UploadedPicture.CopyToAsync(fileStream);
            }
        }

        private async Task<Book> CreateNewBookEntityAsync(string imagePath)
        {
            var authorEntity = await authorData.GetByIdAsync(AuthorId);
            var bookEntity = new Book
            {
                Title = BookModel.Title,
                Pages = BookModel.Pages,
                CurrentPage = BookModel.CurrentPage,
                StartDate = DateTime.Today,
                CoverFilePath = imagePath,

                Author = authorEntity // TODO: Make NOTNULL in db
            };

            return bookEntity;
        }

        private async Task SaveBookEntityToDatabaseAsync(Book bookEntity)
        {
            bookData.Add(bookEntity);
            await bookData.CommitAsync();
        }
    }
}

MyRead.Web/Pages/Manager/Books/Index.cshtml.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc.RazorPages;
using MyRead.Core;
using MyRead.Data;

namespace MyRead.Web.Pages.Books.Manager
{
    public class IndexModel : PageModel
    {
        private readonly IData<Book> bookData;
        
        public IndexModel(IData<Book> bookData)
        {
            this.bookData = bookData;
        }

        public IEnumerable<Book> Books { get; set; }
        
        public void OnGet()
        {
            Books = bookData.GetAll();
        }
    }
}

MyRead.Web/Pages/Manager/Books/Update.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using MyRead.Core;
using MyRead.Data;

namespace MyRead.Web.Pages.Manager.Books
{
    public class UpdateModel : PageModel
    {
        private readonly IData<Book> bookData;

        public UpdateModel(IData<Book> bookData)
        {
            this.bookData = bookData;
        }

        [BindProperty]
        public Book Book { get; set; }

        public void OnGet(int bookId)
        {
            Book = bookData.GetById(bookId); //Null check
        }

        public IActionResult OnPost()
        {
           if(!ModelState.IsValid)
            {
                return Page();
            }

            return RedirectToPage("./Index");
        }
    }
}

MyRead.Web/Pages/Manager/CreateAuthor.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using MyRead.Core;
using MyRead.Core.Models;
using MyRead.Data;

namespace MyRead.Web.Pages.Manager
{
    public class CreateAuthorModel : PageModel
    {
        private readonly IData<Author> authorData;
        public CreateAuthorModel(IData<Author> authorData)
        {
            this.authorData = authorData;
        }

        [BindProperty]
        public AuthorModel AuthorModel { get; set; } 

        public void OnGet()
        {
            AuthorModel = new AuthorModel();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if(!ModelState.IsValid)
            {
                return Page();
            }

            // automapper here
            var authorEntity = new Author
            {
                FirstName = AuthorModel.FirstName,
                LastName = AuthorModel.LastName
            };

            authorData.Add(authorEntity);
            await authorData.CommitAsync();

            return RedirectToPage("./CreateBook");
        }
    }
}

MyRead.Web/Pages/Manager/CreateBook.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using MyRead.Core;
using MyRead.Core.Models;
using MyRead.Data;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace MyRead.Web.Pages.Manager
{
    public class CreateBookModel : PageModel
    {
        private readonly IData<Book> bookData;
        private readonly IData<Author> authorData;
        public CreateBookModel(IData<Book> bookData, IData<Author> authorData)
        {
            this.bookData = bookData;
            this.authorData = authorData;
        }

        [BindProperty]
        public BookModel BookModel { get; set; }

        [Required]
        [BindProperty]
        public int AuthorId { get; set; }

        public List<SelectListItem> AuthorSelect { get; set; }

        public async Task OnGetAsync(int bookId)
        {
            BookModel = new BookModel();

            var authors = await authorData.GetAllAsync();
            AuthorSelect = authors.Select(x => new SelectListItem
            {
                Value = x.AuthorID.ToString(),
                Text = $"{x.LastName}, {x.FirstName}"
            }).ToList();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            // Check if required fields are filled in.
            if (!ModelState.IsValid)
            {
                return Page();
            }

            // temp, use automapper
            var authorEntity = await authorData.GetByIdAsync(AuthorId);
            var bookEntity = new Book
            {
                Title = BookModel.Title,
                Pages = BookModel.Pages,
                CurrentPage = 0
            };

            bookEntity.Author = authorEntity;
            bookData.Add(bookEntity);
            await bookData.CommitAsync();

            return RedirectToPage("./ListBook");
        }
    }
}

MyRead.Web/Pages/Manager/DeleteAuthor.cshtml.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using MyRead.Core.Entities;
using MyRead.Data;

namespace MyRead.Web.Pages.Manager
{
    public class DeleteAuthorModel : PageModel
    {
        private readonly IData<Author> authorData;
        public DeleteAuthorModel(IData<Author> authorData)
        {
            this.authorData = authorData;
        }

        [TempData]
        public string DeleteNotification { get; set; }
        public void OnGet()
        {

        }
        public async Task<IActionResult> OnPost(int authorId)
        {
            var authorEntity = await authorData.GetByIdAsync(authorId);
            
            if(authorEntity != null)
            {
                DeleteNotification = $"Deleted {authorEntity.FirstName} {authorEntity.LastName} from database";

                authorData.Remove(authorEntity);
                await authorData.CommitAsync();
            }            

            return RedirectToPage("./ListAuthor");
        }
    }
}

MyRead.Web/Pages/Manager/ListArchivedBook.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using MyRead.Core.Entities;
using MyRead.Data;
using Serilog;

namespace MyRead.Web.Pages.Manager
{
    public class ListArchivedBookModel : PageModel
    {
        private readonly IData<Book> bookData;
        
        public ListArchivedBookModel(IData<Book> bookData)
        {
            this.bookData = bookData;
        }
        
        public List<Book> ArchivedBooks { get; set; } 

        public async Task OnGet()
        {
            ArchivedBooks = await bookData.GetAll()
                .Where(x => x.IsArchived)
                .Include(x => x.Author)
                .ToListAsync();
        }

        public async Task<IActionResult> OnPostDeleteArchivedBookAsync(int bookId)
        {
            try
            {
                DeleteBook(bookId);
                await SaveChangesToDatabaseAsync();
            }
            catch(Exception ex)
            {
                Log.Logger.Error("Exception in ListArchivedBook OnPostDeleteArchivedBookAsync: " + ex);
            }

            await this.OnGet();
            return Page();
        }

        private void DeleteBook(int bookId)
        {
            var bookToArchive = new Book { BookID = bookId };
            bookData.Remove(bookToArchive);
        }

        public async Task<IActionResult> OnPostUndoArchivedBookAsync(int bookId)
        {
            try
            {
                await UndoArchivedBook(bookId);
                await SaveChangesToDatabaseAsync();
            }
            catch(Exception ex)
            {
                Log.Logger.Error("Exception in ListArchivedBook OnPostUndoArchivedBookAsync: " + ex);
            }
            
            await this.OnGet();
            return Page();
        }

        private async Task UndoArchivedBook(int bookId)
        {
            var bookEntity = await bookData.GetByIdAsync(bookId);
            bookEntity.IsArchived = false;
        }

        private async Task SaveChangesToDatabaseAsync()
        {
            await bookData.CommitAsync();
        }
    }
}

MyRead.Web/Pages/Manager/ListAuthor.cshtml.cs
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using MyRead.Core.Entities;
using MyRead.Data;

namespace MyRead.Web.Pages.Manager
{
    public class ListAuthorModel : PageModel
    {
        private readonly IData<Author> authorData; 
        public ListAuthorModel(IData<Author> authorData)
        {
            this.authorData = authorData;
        }

        [TempData]
        public string DeleteNotification { get; set; }

        public List<Author> Authors { get; set; }
        public void OnGet()
        {
            Authors = authorData.GetAll().ToList();
        }
    }
}

MyRead.Web/Pages/Manager/ListBook.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using MyRead.Core.Entities;
using MyRead.Data;
using Serilog;

namespace MyRead.Web.Pages.Manager
{
    public class ListBookModel : PageModel
    {
        private readonly IData<Book> bookData;

        public ListBookModel(IData<Book> bookData)
        {
            this.bookData = bookData;
        }

        [TempData]
        public string AddNotification { get; set; }

        [TempData]
        public string DeleteNotification { get; set; }

        [TempData]
        public string EditNotification { get; set; }

        public List<Book> Books { get; set; }

        public async Task OnGetAsync()
        {
            Books = await bookData.GetAll()
                .Where(x => !x.IsArchived)
                .Include(x => x.Author)
                .ToListAsync();

        }

        public async Task<IActionResult> OnPostArchiveAsync(int bookId)
        {
            try
            {
                var bookEntity = await bookData.GetByIdAsync(bookId);
                if (bookEntity != null)
                {
                    bookEntity.IsArchived = true;
                    bookEntity.CurrentPage = bookEntity.Pages;
                    bookEntity.EndDate = DateTime.Today;
                    await SaveChangesToDatabaseAsync();
                }
            }
            catch(Exception ex)
            {
                Log.Logger.Error("Exception in ListBook OnPostArchiveAsync: " + ex);
                // TODO: Notification?
            }

            await this.OnGetAsync();
            return Page();
        }

        public async Task<IActionResult> OnPostSetCurrentPageAsync(int bookId, string currentPage)
        {
            try
            {
                var bookEntity = await bookData.GetByIdAsync(bookId);
                if (bookEntity != null && int.Parse(currentPage) <= bookEntity.Pages)
                {
                    bookEntity.CurrentPage = int.Parse(currentPage);
                    await SaveChangesToDatabaseAsync();
                }
            }
            catch(Exception ex)
            {
                Log.Logger.Error("Exception in ListBook OnPostSetCurrentPageAsync: " + ex);
                // TODO: Notification?
            }

            await this.OnGetAsync();
            return Page();
        }

        private async Task SaveChangesToDatabaseAsync()
        {
            await bookData.CommitAsync();
        }
    }
}

MyRead.Web/Pages/Manager/AddAuthor.cshtml
@page
@model MyRead.Web.Pages.Manager.AddAuthorModel
@{
    ViewData["Title"] = "AddAuthor";
}

<h1>CreateAuthor</h1>
<form method="post">
    <div class="form-group">
        <label asp-for="AuthorModel.FirstName"></label>
        <input type="text" asp-for="AuthorModel.FirstName" />
    </div>
    <div class="form-group">
        <label asp-for="AuthorModel.LastName"></label>
        <input asp-for="AuthorModel.LastName" />
    </div>

    <button type="submit" class="alert-primary">Save</button>
</form>

MyRead.Web/Pages/Manager/AddBook.cshtml
@page
@model MyRead.Web.Pages.Manager.AddBookModel
@{
    ViewData["Title"] = "Add Book";
}

<h1>Create</h1>
<form method="post" enctype="multipart/form-data">
    <div class="form-group">
        <label asp-for="@Model.BookModel.Title"></label>
        <input type="text" asp-for="@Model.BookModel.Title" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="@Model.BookModel.CurrentPage"></label>
        <input type="number" asp-for="@Model.BookModel.CurrentPage" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="@Model.BookModel.Pages"></label>
        <input type="number" asp-for="@Model.BookModel.Pages" class="form-control" />
    </div>
    <div class="form-group">
        <label>Author</label>
        <select asp-for="@Model.AuthorId" class="authorSelect"
                asp-items="@Model.AuthorSelect">
            <option value="">--Select Author--</option>
        </select>
    </div>
    <div class="form-group">
        <input type="file" asp-for="@Model.UploadedPicture"  class="form-control" />
    </div>
    <button type="submit" class="btn btn-success">Save</button>
    <a asp-page="./ListBook" class="btn btn-danger">Cancel</a>
</form>
<a asp-page="./AddAuthor" class="btn btn-primary">Add Author</a>


@*Where to place this?*@
@section Scripts {
    <script>
        $(document).ready(function () {
            $(".authorSelect").select2();
        });
    </script>
}

MyRead.Web/Pages/Manager/CreateAuthor.cshtml
@page
@model MyRead.Web.Pages.Manager.CreateAuthorModel
@{
    ViewData["Title"] = "CreateAuthor";
}

<h1>CreateAuthor</h1>
<form method="post">
    <div class="form-group">
        <label asp-for="AuthorModel.FirstName"></label>
        <input type="text" asp-for="AuthorModel.FirstName" />
    </div>
    <div class="form-group">
        <label asp-for="AuthorModel.LastName"></label>
        <input asp-for="AuthorModel.LastName" />
    </div>

    <button type="submit" class="alert-primary">Save</button>
</form>

MyRead.Web/Pages/Manager/CreateBook.cshtml
@page "{bookId:int?}"
@model MyRead.Web.Pages.Manager.CreateBookModel
@{
    ViewData["Title"] = "Edit";
}

<h1>Create</h1>
<form method="post">
    <div class="form-group">
        <label asp-for="@Model.BookModel.Title"></label>
        <input type="text" asp-for="@Model.BookModel.Title" />
    </div>
    <div class="form-group">
        <label asp-for="@Model.BookModel.Pages"></label>
        <input type="number" asp-for="@Model.BookModel.Pages" />
    </div>
    <div class="form-group">
        <label>Author</label>
        <select asp-for="@Model.AuthorId" class="authorSelect"
                asp-items="@Model.AuthorSelect">
            <option value="">--Select Author--</option>
        </select>

    </div>
    <button type="submit" class="alert-primary">Save</button>
</form>
<a asp-page="./CreateAuthor" class="btn btn-primary">Add Author</a>
<a asp-page="./ListBook" class="btn btn-primary">Return</a>


@*Where to place this?*@
@section Scripts {
    <script>
        $(document).ready(function () { 
            $(".authorSelect").select2();
        });
    </script>
}

MyRead.Web/Pages/Manager/DeleteAuthor.cshtml
@page "{authorId:int}"
@model MyRead.Web.Pages.Manager.DeleteAuthorModel
@{
    ViewData["Title"] = "DeleteAuthor";
}

<h1>Really Delete Author</h1>
<form method="post">
    <button type="submit" class="btn btn-danger">Delete</button>
    <a asp-page="./ListAuthor" class="btn btn-primary">Cancel</a>
</form>

MyRead.Web/Pages/Manager/DeleteBook.cshtml
@page "{bookId:int}"
@model MyRead.Web.Pages.Manager.DeleteBookModel
@{
    ViewData["Title"] = "DeleteBook";
}

<h1>Really delete book?</h1>
<form method="post">
    <button type="submit" class="btn btn-danger">Delete</button>
    <a asp-page="./ListBook" class="btn btn-primary">Cancel</a>
</form>

MyRead.Web/Pages/Manager/EditBook.cshtml
@page "{BookId:int}"
@model MyRead.Web.Pages.Manager.EditBookModel
@{
    ViewData["Title"] = "EditBook";
}

<h1>EditBook</h1>
<form method="post" enctype="multipart/form-data">
    <input type="hidden" asp-for="BookModel.BookID" />
    <div class="form-group">
        <label asp-for="BookModel.Title"></label>
        <input asp-for="BookModel.Title" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="BookModel.CurrentPage"></label>
        <input asp-for="BookModel.CurrentPage" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="BookModel.Pages"></label>
        <input asp-for="BookModel.Pages" class="form-control" />
    </div>

    <div class="form-group">
        <label>Author</label>
        <select asp-for="AuthorId" class="authorSelect"
                asp-items="@Model.AuthorSelect">
            <option selected="@Model.BookModel.BookID"></option>
            <option value="">--Select Author--</option>
        </select>
    </div>

    <div class="form-group">
        <input type="file" asp-for="@Model.UploadedImage" class="form-control" />
    </div>

    <button type="submit">Update</button>
    <a class="btn btn-primary" asp-page="./ListBook">Return</a>
</form>

<img src="@Model.ImageFilePath" />

@section Scripts {
    <script>
        $(document).ready(function () {
            $(".authorSelect").select2();
        });
    </script>
}

MyRead.Web/Pages/Manager/ListArchivedBook.cshtml
@page
@model MyRead.Web.Pages.Manager.ListArchivedBookModel
@{
    ViewData["Title"] = "ListArchivedBook";
}

<h1>ListArchivedBook</h1>
<table class="table table-hover">
    <tbody>
        @foreach (var archivedBook in Model.ArchivedBooks)
        {
            <tr>
                <th>
                    @archivedBook.Title
                </th>
                <th>
                    @archivedBook.Author.FirstName @archivedBook.Author.LastName
                </th>
                <th>
                    <form method="post" asp-page-handler="UndoArchivedBook" asp-route-bookId="@archivedBook.BookID">
                        <button type="submit" class="btn btn-primary btn-sm">Unarchive</button>
                    </form>
                </th>
                <th>
                    <form method="post" asp-page-handler="DeleteArchivedBook" asp-route-bookId="@archivedBook.BookID">
                        <button type="submit" class="btn btn-danger btn-sm">Delete</button>
                    </form>
                </th>
            </tr>
        }
    </tbody>    
</table>
<a asp-page="./ListBook" class="btn btn-primary">Back to list</a>

MyRead.Web/Pages/Manager/ListAuthor.cshtml
@page
@model MyRead.Web.Pages.Manager.ListAuthorModel
@{
    ViewData["Title"] = "ListAuthor";
}

<h1>ListAuthor</h1>
<table class="table table-hover">
    <tbody>
        @foreach (var author in Model.Authors)
        {
            <tr>
                <th>
                    @author.FirstName @author.LastName
                </th>
                <th>
                    <a class="btn btn-danger btn-sm" asp-page="./DeleteAuthor" asp-route-authorId="@author.AuthorID">Delete</a>
                </th>
            </tr>
        }
    </tbody>
</table>
<a class="btn btn-primary" asp-page="./ListBook">Back to Books</a>
@if (Model.DeleteNotification != null)
{
    <div class="alert alert-danger">@Model.DeleteNotification</div>
}

MyRead.Web/Pages/Manager/ListBook.cshtml
@page
@model MyRead.Web.Pages.Manager.ListBookModel
@{
    ViewData["Title"] = "List";
}

<h1>Index</h1>
<table class="table table-hover">
    @foreach (var book in Model.Books)
    {
        <tr>
            <th>
                @book.Title
            </th>
            <th>
                @book.Author.FirstName @book.Author.LastName
            </th>
            <th>
                <form method="post" asp-page-handler="SetCurrentPage" asp-route-bookId="@book.BookID">
                    <input type="number" value="@book.CurrentPage" name="currentPage" id="currentPage" />
                    @($"/{book.Pages}")
                </form>
            </th>
            <th>
                <a class="btn btn-primary btn-sm" asp-page="./EditBook" asp-route-bookId="@book.BookID">Edit</a>
            </th>
            <th>
                <a class="btn btn-danger btn-sm" asp-page="./DeleteBook" asp-route-bookId="@book.BookID">Delete</a>
            </th>
            <th>
                <form method="post" asp-page-handler="Archive" asp-route-bookId="@book.BookID">
                    <button type="submit" class="btn btn-secondary btn-sm">Archive</button>
                </form>

            </th>
        </tr>
    }
</table>
<a class="btn btn-primary" asp-page="./AddBook">Add book</a>
<a class="btn btn-info" asp-page="./ListArchivedBook">Archived books</a>
<a class="btn btn-secondary" asp-page="./ListAuthor">Authors</a>

@if (Model.AddNotification != null)
{
    <div class="alert alert-success">@Model.AddNotification</div>
}

@if (Model.DeleteNotification != null)
{
    <div class="alert alert-danger">@Model.DeleteNotification</div>
}

@if (Model.EditNotification != null)
{
    <div class="alert alert-info">@Model.EditNotification</div>
}

@section Scripts {
    <script>
        document.getElementById('currentPage')
            .addEventListener("keyup", function (event) {
                event.preventDefault();
                if (event.keyCode === 13) {
                    document.getElementsByClassName('currentPage').submit();
                }
            });
    </script>
}

MyRead.Web/Pages/Manager/NotFound.cshtml
@page
@{
    ViewData["Title"] = "NotFound";
}

<h1>The resource could not be found</h1>
<a asp-page="ListBook" class="btn btn-outline-primary">Back to Books</a>